export enum FirestoreCollections {
  Admins = 'admins',
  BlogArticles = 'blog-articles',
  BlogAuthors = 'blog-authors',
  BlogCategories = 'blog-categories',
  Categories = 'categories',
  Coupons = 'coupons',
  Customers = 'customers',
  Discounts = 'discounts',
  Orders = 'orders',
  Products = 'products',
  Refunds = 'refunds',
  Settings = 'settings',
  Tags = 'tags',
}
