name: Prod | Deploy CMS
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'cms/**/*'
env:
  PROJECT: wonkawave
  SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WONKAWAVE }}
  TARGET: cms
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Build
        run: npm ci --prefix cms --legacy-peer-deps && npm run build:prod --prefix cms
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: ${{ env.SERVICE_ACCOUNT }}
          channelId: live
          projectId: ${{ env.PROJECT }}
          target: ${{ env.TARGET }}
