name: Prod | Deploy Firestore Indexes
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'firestore.indexes.json'
      - '.github/workflows/indexes.workflow.yml'
env:
  PROJECT: jp-decom
  SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore:indexes --force
        env:
          GCP_SA_KEY: ${{ env.SERVICE_ACCOUNT }}
          PROJECT_ID: ${{ env.PROJECT }}
