name: Prod | Deploy Storage Rules
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'storage.rules'
      - '.github/workflows/storage.yml'
env:
  PROJECT: jp-decom
  SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only storage
        env:
          GCP_SA_KEY: ${{ env.SERVICE_ACCOUNT }}
          PROJECT_ID: ${{ env.PROJECT }}
