name: Update Web
on:
  workflow_dispatch:
    inputs:
      description:
        description: 'Release description'
env:
  PROJECT: jp-decom
  SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
  TARGET: web
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Build
        if: contains(github.ref, 'build')
        run: |
          echo $SV > web/key.json
          npm run build --prefix web
        env:
          SV: ${{ env.SERVICE_ACCOUNT }}
      - name: Deploy
        if: contains(github.ref, 'build')
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: ${{ env.SERVICE_ACCOUNT }}
          channelId: live
          projectId: ${{ env.PROJECT }}
          target: ${{ env.TARGET }}
      - name: Update Firestore
        if: contains(github.ref, 'build')
        run: |
          cd web
          node update-release.cjs
