name: Prod | Deploy Web
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'web/**/*'
env:
  PROJECT: wonkawave
  SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WONKAWAVE }}
  TARGET: web
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Build
        run: npm ci --prefix web --legacy-peer-deps && npm run build --prefix web
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: ${{ env.SERVICE_ACCOUNT }}
          channelId: live
          projectId: ${{ env.PROJECT }}
          target: ${{ env.TARGET }}
      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f --all web/.svelte-kit
          git add -f --all web/node_modules
          git commit -m "BOT - Connected build branch"
      # Remove the build branch in case it already exists
      # this ensures clean code
      - name: Delete build branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ github.token }}
          branches: build
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'build'
          force: true
